### ISSUE TITLE
Does menshen support dynamically loading and unloading function modules?

### ISSUE THREAD

**Issue by daniel0720** [multitenancy-project/menshen#6]
Does menshen support dynamically loading and unloading function modules? If I want to load a new function module, do the existing function modules need to be suspended?

**Comment by wtao0221** [comment]
Basically, Menshen is RMT-like architecture, which provides its own ALUs (e.g., addition, stateful load/store, etc.).

If your "function module" means the new ALU, you have to design it at RTL level and re-conduct the synthesis. If it means you describe a program, which can be translated into the configurations of Menshen, Menshen is designed support this feature at runtime.
